# This variable contains the categories that will be displayed in the categories UI
# the first indented hyphen signifies a row, the second indented hyphen is a column within that row. 
# The number pair is the category id to link to and the head index in that category to use as category image
# Category id 0 means that no category will be displayed there
# The default category UI will look like this:
#
#   +------+------+-------+------+--------+----------+-------+------+------+
#   |      | food |devices| misc |alphabet| interior | color |blocks|      |
#   +------+------+-------+------+--------+----------+-------+------+------+
#   |      |      | mobs  | games|        |characters|pokemon|      |      | 
#   +------+------+-------+------+--------+----------+-------+------+------+
# 
# You can just as easily add custom categories in here. Also note that you don't have
# to add all categories in this overview. The categories that are not in the overview
# are still accessible through the '/headsinv cat <categoryName>' command
# the amount of rows can vary, but the amount of columns always needs to be 9
menuContents: 
    -
        - [0,0]
        - [1,19]
        - [2,0]
        - [3,4]
        - [4,8]
        - [5,18]
        - [6,0]
        - [7,2]
        - [0,0]
    -
        - [0,0]
        - [0,0]
        - [9,9]
        - [8,29]
        - [0,0]
        - [10,31]
        - [11,28]
        - [0,0]
        - [0,0]
