# used for new version detection
version: ${project.version}

# This variable contains the categories that will be displayed in the categories UI
# the first indented hyphen signifies a row, the second indented hyphen is a column within that row. 
# The number pair is the category id to link to and the head index in that category to use as category image
# Category id 0 means that no category will be displayed there
# The default category UI will look like this:
#
#   +--------------+-----------+-------+----------+----------+--------+--------+-------------+-----+
#   |     food     | alphabet  |pokemon| interior |characters|  mobs  |devices |     misc    |color|
#   +--------------+-----------+-------+----------+----------+--------+--------+-------------+-----+
#   | food-drinks  |  blocks   |animals|decoration|  humans  |humanoid|monsters|miscellaneous|Games|
#   +--------------+-----------+-------+----------+----------+--------+--------+-------------+-----+
#   |              |           |       |          |          |        |        |             |     |
#   +--------------+-----------+-------+----------+----------+--------+--------+-------------+-----+
# 
# You can just as easily add custom categories in here. Also note that you don't have
# to add all categories in this overview. The categories that are not in the overview
# are still accessible through the '/headsinv cat <categoryName>' command
# the amount of rows can vary, but the amount of columns always needs to be 9
menuContents: 
    -
        - [food,19]
        - [alphabet,8]
        - [pokemon,28]
        - [interior,18]
        - [characters,31]
        - [mobs,9]
        - [devices,0]
        - [misc,4]
        - [color,0]
    -
        - [food-drinks,0]
        - [blocks,2]
        - [animals,5]
        - [decoration,52]
        - [humans,16]
        - [humanoid,13]
        - [monsters,133]
        - [miscellaneous,22]
        - [games,26]
    -
        - [empty,0]
        - [empty,0]
        - [empty,0]
        - [empty,0]
        - [empty,0]
        - [empty,0]
        - [empty,0]
        - [empty,0]

locale: en_US