name: HeadsInventory
version: ${version}
api-version: 1.13
main: com.github.cc007.headsinventory.HeadsInventory
author: Rik Schaaf aka CC007 (http://coolcat007.nl/)
description: >
             Search for heads in the 
depend: [HeadsPluginAPI]
commands:
    headsinventory:
        description: "Search for heads"
        aliases: [hdsinv, headsinv, hdsinventory, sps, skull]
    myhead:
        description: "Receive your own head"
        aliases: [myhd]
    addhead:
        description: "Add a new head to the database"
        aliases: [addhd]
    playerhead:
        description: "Receive another player's head"
        aliases: [plyrhd]
    updateheads:
        description: "update the cached heads"
        aliases: [updatehds]
    heads:
        description: "shows help page"
        aliases: []
permissions:
    headsinv.myhead:
        description: Allows the user to get their own head
    headsinv.playerhead:
        description: Allows the user to get another player's head
    headsinv.inventory:
        description: Allows the user to use the heads inventory
    headsinv.update:
        description: Allows the user to update the heads categories
    headsinv.search:
        description: Allows the user to search directly for heads from the database
    headsinv.add:
        description: Allows the user to add a new head to the database
    headsinv.help:
        description: Allows the user to see the help page
